### ISSUE TITLE
Does not allow moving the tabs between vertical monitors

### ISSUE THREAD

**Issue by jlfernandez-elipgo** [Unreal852/EasyTabs#1]
Hi

If the monitors are organized up/down, it does not accept to move it by dragging the window vertically, it allows to drag it only between monitors horizontally.

![91324075-04374e00-e798-11ea-9109-f36c6cf0c409](https://user-images.githubusercontent.com/70984936/92537701-2955a300-f213-11ea-8efa-fb729214ca96.png)

Thanks!

**Comment by Unreal852** [comment]
I just tried and it works fine on my side, thats weird

**Comment by jlfernandez-elipgo** [comment]
Thank you very much, you are right with your library it works.
With the original this functionality does not work.

**Comment by Unreal852** [comment]
Happy to hear that !
